//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Import.Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Import.Service.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loader service {0} need reset, but it was already reset. Import {1} was stopped..
        /// </summary>
        internal static string ImportWasStoppedLoaderServiceAlreadyReseted {
            get {
                return ResourceManager.GetString("ImportWasStoppedLoaderServiceAlreadyReseted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebLoader {0} was not executed. Import was stopped..
        /// </summary>
        internal static string ImportWasStoppedWebLoaderNotExecute {
            get {
                return ResourceManager.GetString("ImportWasStoppedWebLoaderNotExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loader is reseting....
        /// </summary>
        internal static string LoaderIsReseting {
            get {
                return ResourceManager.GetString("LoaderIsReseting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer {0} not started.Warning : {1}..
        /// </summary>
        internal static string LoaderNotStartedWarning {
            get {
                return ResourceManager.GetString("LoaderNotStartedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loader reset successfully..
        /// </summary>
        internal static string LoaderResetSuccessfully {
            get {
                return ResourceManager.GetString("LoaderResetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loader service {0} was reset with error {1}..
        /// </summary>
        internal static string LoaderServiceResetingFailed {
            get {
                return ResourceManager.GetString("LoaderServiceResetingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading from url {0} completed with error {1} and need in reseting..
        /// </summary>
        internal static string LoadFromUrlCompletedWithErrorAndNeedReset {
            get {
                return ResourceManager.GetString("LoadFromUrlCompletedWithErrorAndNeedReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process url {0} failed.
        /// </summary>
        internal static string ProcessUrlFailedError {
            get {
                return ResourceManager.GetString("ProcessUrlFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process url {0} not complete. Warning : {1}..
        /// </summary>
        internal static string ProcessUrlNotCompleteWarning {
            get {
                return ResourceManager.GetString("ProcessUrlNotCompleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request url {0} failed with error {1}. Loader will be paused on {2} milliseconds..
        /// </summary>
        internal static string RequestFailedAndLoaderWillBePaused {
            get {
                return ResourceManager.GetString("RequestFailedAndLoaderWillBePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request url {0} failed with error :  {1}.
        /// </summary>
        internal static string RequestUrlFailedWithError {
            get {
                return ResourceManager.GetString("RequestUrlFailedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} started..
        /// </summary>
        internal static string ServiceStarted {
            get {
                return ResourceManager.GetString("ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} was cancelled..
        /// </summary>
        internal static string ServiceWasCancelled {
            get {
                return ResourceManager.GetString("ServiceWasCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} was cancelled. {1}..
        /// </summary>
        internal static string ServiceWasCancelledOn {
            get {
                return ResourceManager.GetString("ServiceWasCancelledOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} was cancelled on loading from url {1}..
        /// </summary>
        internal static string ServiceWasCancelledOnLoadingFromUrl {
            get {
                return ResourceManager.GetString("ServiceWasCancelledOnLoadingFromUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} was cancelled on loading from url {1} by error {2}..
        /// </summary>
        internal static string ServiceWasCancelledOnLoadingFromUrlByError {
            get {
                return ResourceManager.GetString("ServiceWasCancelledOnLoadingFromUrlByError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} was stopped..
        /// </summary>
        internal static string ServiceWasStopped {
            get {
                return ResourceManager.GetString("ServiceWasStopped", resourceCulture);
            }
        }
    }
}
